services:
  - type: web
    name: kenos-corner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    rootDir: . 